{% set name = "RASPA2" %}
{% set version = "2.0.50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/iRASPA/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e831ea5325713b33333dd7cf89f5587386922a250b16fa7ec4d1eee3a53a29dd

build:
  number: 0
  skip: true  # [ win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
    - autoconf
    - automake
    - libtool
  host:
    - libblas
    - liblapack
    - fftw

test:
  commands:
    - simulate -v
    - simulate -h

about:
  home: https://github.com/iRASPA/RASPA2
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Classical molecular simulation code

  description: |
    RASPA2 can be used for the simulation of molecules in gases, fluids, zeolites, aluminosilicates, metal-organic frameworks, carbon nanotubes and external fields.
  doc_url: https://github.com/iRASPA/RASPA2
  dev_url: https://github.com/iRASPA/RASPA2

extra:
  recipe-maintainers:
    - ltalirz
