{% set name = "RASPA2" %}
{% set version = "2.0.47" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/iRASPA/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1a14524f95ab86e7a2910b53641262ec98ec23f794f1c3665982c32efc1997ed

build:
  number: 0
  skip: true  # [ win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - autoconf
    - automake
    - libtool
  host:
    - libblas
    - liblapack
    - fftw

test:
  commands:
    - simulate -v
    - simulate -h

about:
  home: https://github.com/iRASPA/RASPA2
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Classical molecular simulation code

  description: |
    RASPA2 can be used for the simulation of molecules in gases, fluids, zeolites, aluminosilicates, metal-organic frameworks, carbon nanotubes and external fields.
  doc_url: https://github.com/iRASPA/RASPA2
  dev_url: https://github.com/iRASPA/RASPA2

extra:
  recipe-maintainers:
    - ltalirz
